title: Beau Hodes
description: Test description
name: Beau Hodes
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
        css_class: 'highlight'
permalink: /articles/:year/:month/:day/:title
#google_analytics: G-9JGKLTXJ00
