title: Beau Hodes
description: Test description
name: Beau Hodes
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
permalink: /articles/:year/:month/:day/:title
#google_analytics: G-9JGKLTXJ00
